language: go

go:
  - 1.15

before_install:
  - go get golang.org/x/tools/cmd/cover # coveralls.io
  - go get github.com/mattn/goveralls   # coveralls.io

script:
  - go test -race ./...
  - $GOPATH/bin/goveralls -service=travis-ci # coveralls.io

after_script:
  - curl -d "repo=github.com/AsaiYusuke/jsonpath" https://goreportcard.com/checks
  